services:
  - type: web
    name: stalcraft-bot-api
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    branch: main
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: 8389074990:AAHz7e6KaZRbrPSswz6L2GQObo9c3PudVIc